apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: microservices-project-2
build: 
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: gkibria121/auth 
      context: ./auth
      docker:
        dockerfile: ../dockerfiles/Dockerfile 
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gkibria121/client 
      context: ./client
      docker:
        dockerfile:  Dockerfile 
       
      sync:
        manual:
          - src: 'app/**/*.tsx' 
            dest: .
          - src: 'app/**/*.ts'
            dest: .
          - src: 'app/**/*.jsx' 
            dest: .
          - src: 'app/**/*.js'
            dest: .
          - src: 'src/**/*.tsx' 
            dest: .
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.jsx' 
            dest: .
          - src: 'src/**/*.js'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*
