apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration
spec:
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
      - name: expiration
        image: gkibria121/microservices-project-2-expiration
        # imagePullPolicy: IfNotPresent
        env: 
          - name: CLUSTER_ID 
            value: "nats-streaming"
          - name: NATS_URL 
            value: "http://nats-streaming-service:4222"
          - name: REDIS_HOST 
            value: "redis://redis-srv:6379" 
        resources:
          requests:
              memory: "256Mi"
              cpu: "500m" 
          limits:
            memory: "512Mi"
            cpu: "500m" 